/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 13 15:22:31 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class KeyIndexedSorting_ESTest extends KeyIndexedSorting_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      KeyIndexedSorting keyIndexedSorting0 = new KeyIndexedSorting();
      keyIndexedSorting0.R = (-1183);
      // Undeclared exception!
      try { 
        keyIndexedSorting0.toIndices();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("KeyIndexedSorting", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      KeyIndexedSorting keyIndexedSorting0 = new KeyIndexedSorting();
      keyIndexedSorting0.N = (-570);
      keyIndexedSorting0.countFrequency();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      KeyIndexedSorting keyIndexedSorting0 = new KeyIndexedSorting();
      keyIndexedSorting0.N = 0;
      keyIndexedSorting0.toRecords();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      KeyIndexedSorting keyIndexedSorting0 = new KeyIndexedSorting();
      keyIndexedSorting0.N = 0;
      keyIndexedSorting0.toIndices();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      KeyIndexedSorting keyIndexedSorting0 = new KeyIndexedSorting();
      Student[] studentArray0 = new Student[9];
      Student student0 = new Student("lDt*ZGa~aWi_5", (-4));
      studentArray0[0] = student0;
      studentArray0[1] = student0;
      studentArray0[2] = studentArray0[0];
      studentArray0[3] = studentArray0[2];
      studentArray0[4] = student0;
      studentArray0[5] = student0;
      studentArray0[6] = studentArray0[3];
      studentArray0[7] = studentArray0[0];
      studentArray0[8] = student0;
      keyIndexedSorting0.aux = studentArray0;
      keyIndexedSorting0.copyBack();
      // Undeclared exception!
      try { 
        keyIndexedSorting0.toRecords();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -4
         //
         verifyException("KeyIndexedSorting", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      KeyIndexedSorting keyIndexedSorting0 = new KeyIndexedSorting();
      Student[] studentArray0 = new Student[3];
      keyIndexedSorting0.aux = studentArray0;
      // Undeclared exception!
      try { 
        keyIndexedSorting0.toIndices();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 3
         //
         verifyException("KeyIndexedSorting", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      KeyIndexedSorting keyIndexedSorting0 = new KeyIndexedSorting();
      keyIndexedSorting0.a = null;
      // Undeclared exception!
      try { 
        keyIndexedSorting0.show();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("KeyIndexedSorting", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      KeyIndexedSorting keyIndexedSorting0 = new KeyIndexedSorting();
      Student[] studentArray0 = new Student[8];
      keyIndexedSorting0.a = studentArray0;
      // Undeclared exception!
      try { 
        keyIndexedSorting0.countFrequency();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("KeyIndexedSorting", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      KeyIndexedSorting keyIndexedSorting0 = new KeyIndexedSorting();
      // Undeclared exception!
      try { 
        keyIndexedSorting0.countFrequency();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 5
         //
         verifyException("KeyIndexedSorting", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      KeyIndexedSorting keyIndexedSorting0 = new KeyIndexedSorting();
      Student[] studentArray0 = new Student[3];
      keyIndexedSorting0.aux = studentArray0;
      // Undeclared exception!
      try { 
        keyIndexedSorting0.copyBack();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 3
         //
         verifyException("KeyIndexedSorting", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      KeyIndexedSorting keyIndexedSorting0 = new KeyIndexedSorting();
      keyIndexedSorting0.show();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      KeyIndexedSorting keyIndexedSorting0 = new KeyIndexedSorting();
      // Undeclared exception!
      try { 
        keyIndexedSorting0.copyBack();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("KeyIndexedSorting", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      KeyIndexedSorting keyIndexedSorting0 = new KeyIndexedSorting();
      // Undeclared exception!
      try { 
        keyIndexedSorting0.toRecords();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("KeyIndexedSorting", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      KeyIndexedSorting keyIndexedSorting0 = new KeyIndexedSorting();
      keyIndexedSorting0.N = 3;
      keyIndexedSorting0.countFrequency();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String[] stringArray0 = new String[4];
      // Undeclared exception!
      try { 
        KeyIndexedSorting.main(stringArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 5
         //
         verifyException("KeyIndexedSorting", e);
      }
  }
}
