/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 13 15:19:26 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LSD_ESTest extends LSD_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = ";o]<:\"{i`=I]R3";
      stringArray0[1] = "yT|y^\"G<WH'qn5m-Rn";
      LSD.sort(stringArray0, 1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      LSD.sort(stringArray0, 467);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = ";o]<:\"{i`=I]R3";
      // Undeclared exception!
      try { 
        LSD.sort(stringArray0, 832);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        LSD.sort((String[]) null, 4687);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("LSD", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LSD lSD0 = new LSD();
  }
}
