/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 13 15:22:51 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LSDSorting_ESTest extends LSDSorting_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LSDSorting.main((String[]) null);
      LSDSorting.main((String[]) null);
      LSDSorting.main((String[]) null);
      LSDSorting.main((String[]) null);
      LSDSorting.main((String[]) null);
      // Undeclared exception!
      LSDSorting.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LSDSorting lSDSorting0 = new LSDSorting();
  }
}
